### ISSUE TITLE
yaml_rust2 0.8.1 breaks `tests::matter_read::test_parse_complex_yaml_front_matter` 

### ISSUE THREAD

**Issue by Xuanwo** [the-alchemists-of-arland/gray-matter-rs#20]
Hi, I found `yaml_rust2 0.8.1` breaks `tests::matter_read::test_parse_complex_yaml_front_matter`.

All tests passed while using `yaml_rust2 0.8.0`, but after yaml_rust2 upgraded to `0.8.1`. Test failed:

```shell
thread 'tests::matter_read::test_parse_complex_yaml_front_matter' panicked at src/tests/matter_read.rs:72:84:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::matter_read::test_parse_complex_yaml_front_matter

test result: FAILED. 28 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

The parsed entity will be:

```
---- tests::matter_read::test_parse_complex_yaml_front_matter stdout ----
[src/matter.rs:163:9] &parsed_entity = ParsedEntity {
    data: Some(
        Null,
    ),
    content: "<span class=\"alert alert-info\">This is an alert</span>\n\n## YAML ...."
```

**Comment by Xuanwo** [comment]
The root case seems related to `YamlLoader::load_from_str(content)`. yaml will return err now:

```
---- tests::matter_read::test_parse_complex_yaml_front_matter stdout ----
[src/engine/yaml.rs:20:17] "parse failed: " = "parse failed: "
[src/engine/yaml.rs:20:17] err = ScanError {
    mark: Marker {
        index: 2004,
        line: 80,
        col: 16,
    },
    info: "String(\"domain\"): duplicated key in mapping",
}
thread 'tests::matter_read::test_parse_complex_yaml_front_matter' panicked at src/tests/matter_read.rs:72:84:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Xuanwo** [comment]
Ok, I got. Our test fixtures are wrong:

- https://raw.githubusercontent.com/the-alchemists-of-arland/gray-matter-rs/main/src/tests/fixtures/complex.md
- https://raw.githubusercontent.com/jonschlinkert/gray-matter/master/test/fixtures/complex.md

Indent matters in YAML.
